### ISSUE TITLE
Layout responsivo

### ISSUE THREAD

**Issue by gallegogti** [deivisonarthur/OSC-Magento-Brasil-6-Pro#101]
Boa tarde pessoal,

Primeiramente parabens ao Deividson pelo projeto e o Rafaelstz por ajudar a todos!

Estou tendo problemas com o layout em telas menores, como em celulares.

Exemplo: http://tinypic.com/view.php?pic=2a81d20&s=8

Como vocês conseguiram resolver?

Obrigado

**Comment by rafaelstz** [comment]
Olá @gallegogti obrigado pelas considerações! :smile: 
Você pode colocar  `float: left; width: 33%`  em cada bloco.

**Comment by gallegogti** [comment]
Valeu pelas dicas @rafaelstz !

Vou estudar um pouco e conseguindo, coloco aqui.

Abs!

**Comment by gallegogti** [comment]
Tudo funcionando! valeu @rafaelstz !

**Comment by rafaelstz** [comment]
:+1: :smile:

**Comment by diogodaluz** [comment]
Solução que funcionou aqui passo a passo (imagino que tenha melhores formas mas assim funcionou):

Passo1 ) Adicione ao seu arquivo CSS:

    .versoes {
        width: 32% !important;
    }
    @media screen and (max-width: 800px) { 
        .versoes {
             
             width: 100% !important;

        }
    }

Passo 2) Adicione ao arquivo /app/design/frontend/base/default/template/onestepcheckout/onestep.phtml

<div class="col-1"> Substituir por: <div class="col-1 versoes">
<div class="col-2"> Substituir por: <div class="col-2 versoes">
<div class="col-3"> Substituir por: <div class="col-3 versoes">

**Comment by cidsant** [comment]
Alguem pode por favor me explicar como fazer isso?
Sou novo em magento e css então não entendi como faço para ajustar a tela do celular.

**Comment by diogodaluz** [comment]
Tutorial completo no site: 
http://www.usemagento.com.br/como-deixar-o-layout-responsivo-no-one-step-checkout-6-brasil/

**Comment by cidsant** [comment]
muito obrigado!

**Comment by edica** [comment]
Muito bom Diogo! Obrigado!

**Comment by claudioalberto13** [comment]
Boa Noite

Pessoal, alguem poderia me ajudar, o meu tema e o igame, segui o tutorial, porem ele não subiu certo.
Vi que meu tema utiliza Bootstrap, muda alguma coisa ?
