### ISSUE TITLE
Problemas ao usar cupons

### ISSUE THREAD

**Issue by redhurt** [deivisonarthur/OSC-Magento-Brasil-6-Pro#111]
É necessário que os valores de frete sejam atualizados após utilizar um cupom. Criei um cupom com a opção frete grátis e reparei que o bloco de shipping não atualiza após utilizar o mesmo. Alguém sabe me dizer o comando que faz isso?

**Comment by davirs** [comment]
cara, não sei se isso é pau do magento, se é assim mesmo, se é o checkout que esta puxando errado...
mas pra resolver isso, você tem que colocar "R$" na frente do valor, se você está usando subtotal para criar a regra... 

![frete gratis](https://cloud.githubusercontent.com/assets/4355062/7380738/e8aeff66-edd3-11e4-9e30-3cd6688bb702.png)

**Comment by redhurt** [comment]
O cupom não tem nenhuma condição. Só defini que o cliente que usar o cupom XYZ ganhe frete grátis. No resumo, que é atualizado após usar o cupom, o valor do frete recebe o desconto, porém o bloco do frete não atualiza e fica com o valor do frete normal, sem o desconto. Se eu atualizo a página manualmente aí o frete vem com o desconto...

**Comment by davirs** [comment]
mas atualiza cara... quando vc insere o cupom tem que aparecer uma mensagem se ele foi aceito ou não. Se foi aceito ele da o reload ali nos blocos. fica lá as opções de frete com valor 0(zero). 
pode ser teu tema com problema
algum conflito JS etc...
desculpa não poder ajudar mais

**Comment by redhurt** [comment]
então...
Quando uso o cupom ele atualiza o payment e o review mas o shipping não. Aí tá diferente?

**Comment by davirs** [comment]
como disse, aqui atualiza o boco do shipping tbm.

**Comment by redhurt** [comment]
Valeu brother!
Vou continuar verificando aqui o que pode estar dando problema...

**Comment by redhurt** [comment]
Tá usando qual versão de Magento?

**Comment by davirs** [comment]
v1.9.0.1

**Comment by lacerdabh** [comment]
...............

**Comment by davirs** [comment]
Cara, você pode testar pra mim uma regra de 50% de desconto(por exemplo)?

coloca uns 4 produtos no carrinho e no checkout coloque o cupom com a regra...
aqui ele só aplica essa regra no primeiro item...
não consegui fazer funcionar para o subtottal de jeito nenhum...

**Comment by bemColar** [comment]
..

Em 22 de maio de 2015 20:24, davirs <notifications@github.com> escreveu:

> Cara, você pode testar pra mim uma regra de 50% de desconto(por exemplo)?
>
> coloca uns 4 produtos no carrinho e no checkout coloque o cupom com a
> regra...
> aqui ele só aplica essa regra no primeiro item...
> não consegui fazer funcionar para o subtottal de jeito nenhum...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/deivisonarthur/OSC-Magento-Brasil-6-Pro/issues/111#issuecomment-104799049>
> .
>



--

**Comment by redhurt** [comment]
cara aqui o desconto tá aplicando normal...
O único problema com cupom aqui é que quando uso um cupom ele não atualiza o bloco de entrega e caso eu crie um cupom de frete grátis aí fudeu!

**Comment by davirs** [comment]
eu descobri o meu problema aqui. é a extensão custom options da mageworx... ela modifica algumas regras de preço dai quando chega no checkout da pau no desconto...
valeu por testar fera

**Comment by redhurt** [comment]
Reparei que o resumo da compra é atualizado. O bloco shipping nas versões anteriores ficava zerado quando eu fazia esse procedimento....
