### ISSUE TITLE
Checkout com erro. Tela em branco.

### ISSUE THREAD

**Issue by deustaquio** [deivisonarthur/OSC-Magento-Brasil-6-Pro#114]
Boa noite pessoal.

Estou com o seguinte problema no OSC 6 com Magento 1.9.1.0. Ao clicarmos em "Finalizar Compra" aparece uma tela em branco "/onestepcheckout/index/". 

O debug apresenta o seguinte erro:

a:5:{i:0;s:59:"Modelo base "" não encontrado para o atributo "tipopessoa"";i:1;s:4247:"#0 /var/www/vhosts/celebrate.com.br/httpdocs/loja2015/app/code/core/Mage/Eav/Model/Entity/Attribute/Abstract.php(387): Mage::exception('Mage_Eav', 'Modelo base "" ...')
#1 /var/www/vhosts/celebrate.com.br/httpdocs/loja2015/app/design/frontend/base/default/template/onestepcheckout/customer/form/edit.phtml(17): Mage_Eav_Model_Entity_Attribute_Abstract->getSource()

Uma simulação pode ser realizada neste link http://celebrate.com.br/loja2015/papel-comestivel-a3-29-7-x-42-cm-pct-c-50-un.html

Alguém pode me ajudar com este bug?

Obrigado.

**Comment by rafaelstz** [comment]
Colocando no tema padrão do Magento o bug continua?
Deixando no template padrão mesmo do Magento, vá na Index.php e descomenta a ativação do **DeveloperMode**, aparece que mensagem?

**Comment by deustaquio** [comment]
Bom dia Rafael.
Com o tema padrão também acontece a mesma coisa. Também desativamos todos os outros módulos, mas o erro permanece.
Vou fazer o teste com a ativação do DeveloperMode e já te falo.
Obrigado

**Comment by deustaquio** [comment]
O DeveloperMode está ativo, mas não aparece nenhuma mensagem de erro.

if (isset($_SERVER['MAGE_IS_DEVELOPER_MODE'])) {
    Mage::setIsDeveloperMode(true);
}

Fiz um teste se estar logado no frontend e o chackout aparece, mas quando efetuo login ou faço um novo cadastro fica em branco novamente.

**Comment by deustaquio** [comment]
Como visitante no tema padrão o processo de compra está funcionando, mas quando efetuamos o login fica com a tela em branco.

**Comment by deustaquio** [comment]
Rafael, conseguimos resolver o problema. Era tão óbvio que achamos que era outra coisa.
Foi só aumentarmos o memory_limit que o problema se resolveu.
Muito obrigado pelo auxílio.

Abçs

**Comment by rafaelstz** [comment]
Disponha :smile: :+1:

**Comment by filimm** [comment]
Mas o que o aumento de memória tem a ver com esse erro ??

**Comment by rafaelstz** [comment]
@filimm O Magento tem um limite de memória aconselhado para rodar, que não condiz com a maioria dos servidores por padrão.

**Comment by absolutodigital** [comment]
nao faz sentindo isso, estou com o mesmo erro

**Comment by hansbonini** [comment]
Claro que faz, a maioria dos usuarios usa hospedagem improprias para magento, como godaddy, hostgator... o ideal e um AWS, Google Compute Engine ou Nexcess. Tem um artigo sobre isso no topico do Mario SAM
