### ISSUE TITLE
Como aumentar a altura do bloco de Login/Esqueci Senha?

### ISSUE THREAD

**Issue by fernandoperigolo** [deivisonarthur/OSC-Magento-Brasil-6-Pro#115]
Pessoal, estou fazendo uma customização no checkout e não estou entendendo o que devo fazer para aumentar a altura daquele bloco de login e recuperar senha?

Vi que no JS ele pega a altura automaticamente e faz o efeito de mostrar/esconder os blocos. Alguma dica?

**Comment by rafaelstz** [comment]
você consegue colocar **!important** via CSS
