### ISSUE TITLE
Verifique se repetiu a senha corretamente.

### ISSUE THREAD

**Issue by JonatanM** [deivisonarthur/OSC-Magento-Brasil-6-Pro#117]
Ola
Acabei de verificar que estou com um erro que mesmo estando com a senha e a confirmação igual a validação falha "Verifique se repetiu a senha corretamente." verifiquei que poderia ser o modulo da MOIP  mais eu nao tenho esse modulo instalado, tenho o Onestepcheckout Brasil, a loja esta em produção e sempre funcionou a unica coisa que eu fiz foi aplicar os 3 patch de segurança. e no ultimo que eu reparei o problema.
E pior que não esta gerando nem um log
 
Abraços,
Jonatan Machado

**Comment by JonatanM** [comment]
Achei uma solução em um forum gringo  mais não e uma solução rsrrs ele mada alterar o core e eu verifiquei foi esse foi um dos arquivos que foi atualizado no ultimo patch claro que nao vou alterar.

Hi Friends This Problem Can be resolved by doing below steps:
Step 1: Open This file /app/code/core/Mage/Customer/Model/Customer.php 
Step 2: Find This line in Customer.php $confirmation = $this->getPasswordConfirmation(); 
Step 3: Replace That that line with $confirmation = $this->getConfirmation(); Huh Your Problem is now Resolved.

**Comment by JonatanM** [comment]
O modulo faz essa validação? ou é do magento?
ainda nao consegui achar o problema :(

**Comment by JonatanM** [comment]
Tive que fazer o teste alterei o arquivo do core e funciona. Porem não seu se isso e correto pois qual alterou aparte do código foi uma atualização critica do magento. porem parece que não funciona na verção magento 1.9.0.1

**Comment by JonatanM** [comment]
Achei esse link para alguém que quiser mais informações
http://www.magikcommerce.com/blog/fix-please-make-sure-password-match-issue-magento-1-9-1-0/

**Comment by Stormcloud** [comment]
É possível corrigir esse problema sem alterar o core.
No arquivo `app\code\local\DeivisonArthur\OnepageCheckout\Model\Type\Geo.php`, altere a linha que diz:
`'confirmation' => 'confirm_password',`
para:
`'password_confirmation' => 'confirm_password',`
