### ISSUE TITLE
Como pegar os dados de IE / RG ?

### ISSUE THREAD

**Issue by kimtiago** [deivisonarthur/OSC-Magento-Brasil-6-Pro#118]
Olá,

este não é um bug do OSC, mas acho que não tem lugar melhor pra perguntar do que aqui.

Estou integrando o Bling com minha loja magento que usa OSC6. Preciso passar via SOAP o campo IE / RG para o Bling, porém não sei como posso extrair isso. O TAXVAT (CPF) eu consigo através do comando

$order->getData('customer_taxvat');

mas não consigo descobrir como pegar o campo IE / RG, alguém pode dar uma luz?

**Comment by leogold** [comment]
O bling já tem a opção de chamar estes campos nativamente, basta vc colocar o nome da variável no bling na configuração do magento nos campos personalizados. É isso que precisa?

**Comment by rafaelstz** [comment]
:top: :+1:

**Comment by kimtiago** [comment]
não é somente isso, tem que alterar a API de vendas para passar estas informações pro bling. o arquivo está em "app/code/core/Mage/Sales/Model/Order/Api.php"

assim

![screen shot 05-26-15 at 06 01 pm](https://cloud.githubusercontent.com/assets/11681263/7824495/44fd2bb8-03d1-11e5-9715-816d68648189.PNG)

este é codigo da minha ultima tentativa de botar pra funcionar... os campos de endereço e o CPF estão funcionando, mas IE e RG não, já tentei adivinhar como chamar de diversas formas... é enviado NULL para os servidores do Bling. Se eu alterar o conteudo para '11111111' este valor é enviado. O problema está no método para pegar esta informação que eu não sei como fazer.

estou seguindo o tutorial com do proprio bling aqui http://www.bling.com.br/manuais.bling.php?p=api.magento.desenvolvedor

**Comment by leogold** [comment]
Pego o campo, ean, ncm que criei assim. Bem tranquilo. Mudei tb os de densoea do produto. Bem tranquilo. Não pego o rg Pq não uso. Mas deve ser igual, não?

**Comment by kimtiago** [comment]
Mano desculpa, eu não entendi o q vc escreveu. "Mudei tb os de densoea do produto."

Igual de que forma?

**Comment by philspbr** [comment]
Olá Kim,

Fiz essa integração no passado, você não pode pegar o valor do atributo tipopessoa direto do pedido pois ele não está gravado na tabela do pedido. Você precisa carregar o cliente primeiro:
$customerId = $this->$order->getCustomerId();
$tipoPessoa = Mage::getModel('customer/customer')->load($customerId)->getTipopessoa();
Qualquer dúvida me chame no skype 'elcaballero1' 

Abs,
Philipp

**Comment by kimtiago** [comment]
Agradeço a ajuda dos colegas, o philipp deu o empurrão que eu precisava. Deixo aqui a solução para as próximas pessoas que provavelmente vão ter este dúvida.

Junto com as outras linha de código na API deve-se adicionar as seguintes linhas de comando antes do "return $result" do arquivo "app/code/core/Mage/Sales/Model/Order/Api.php"

$customerId = $order->getCustomerId();
$customer = Mage::getModel('customer/customer')->load($customerId);
$result['rg_personalizado'] = $customer->getData('ie');
$result['ie_personalizado'] = $customer->getData('ie');

Obs: No OSC6 o campo IE corresponde aos tanto a IE quanto ao RG.
