### ISSUE TITLE
Cliente redirecionado para o historico de pedidos

### ISSUE THREAD

**Issue by arnonsoares** [deivisonarthur/OSC-Magento-Brasil-6-Pro#150]
Fala Galera!

To com um pequeno problema. O cliente clica no produto, coloca no carrinho, e faz o login na conta (isso para clientes já cadastrados). O problema é que depois que eles faz o login, o cliente é redirecionado para a pagina de históricos de pedido (painel de controle do cliente), e não para a página do checkout.

Alguem sabe como posso resolver isso?
Creio que esteja havendo apenas um erro de redirecionamento.

**Comment by isaaclopes** [comment]
Ola, @arnonsoares da uma olha no admin do sua loja em

admin > sistema > configuracao;
Aba cliente do lado esquerdo;
"opção de acesso" > Redirecione Cliente para o Painel de Conta após a Acessar;
deixa como NÃO

**Comment by arnonsoares** [comment]
Muito Obrigado Isaaclopes!
Funcionou perfeitamente!
