### ISSUE TITLE
Max Length para Campo Street 3

### ISSUE THREAD

**Issue by fernandoperigolo** [deivisonarthur/OSC-Magento-Brasil-6-Pro#162]
Pessoal, o campo street3, usado para complemento, tem uma limitação via JS de 20 caracteres.
Minha dúvida é, é possível aumentar o tamanho deste campo? Ou ele tem este tamanho(20) por conta de uma limitação do BD ou algo assim?

Minha ideia é colocar 40, como o street1, é seguro?

**Comment by rafaelstz** [comment]
Sim é seguro, pode alterar via código.
Não vou saber te dizer exatamente a linha de cabeça, mas pode fazer. :smile:

**Comment by fernandoperigolo** [comment]
Valeu, obrigado.
