### ISSUE TITLE
Lista de Estados não aparece

### ISSUE THREAD

**Issue by fabisoccol** [deivisonarthur/OSC-Magento-Brasil-6-Pro#163]
Olá pessoal, tudo bom?

Eu já uso o módulo antigo em uma loja minha (www.echarme.com.br), mas estou desenvolvendo uma loja para um cliente e baixei o OSC 6.

Estou tendo problema na visualização do dropdown dos estados. Ele não aparece e assim nada além dele também.

O endereço do site em testes é: http://www.cozinhandoogalo.com.br.

Espero que possam me ajudar.

**Comment by rafaelstz** [comment]
Verifique a semântica.
![image](https://cloud.githubusercontent.com/assets/610598/10918332/393863f2-824c-11e5-8f18-cd02ad9cd16f.png)

**Comment by fabisoccol** [comment]
Oi @rafaelstz , tudo jóia? Muito obrigada pelo retorno, mas acho que vou precisar de uma explicação mais didática... risos... Sou um pouco leiga em algumas coisas e essa é uma delas!

Você poderia me explicar melhor?

**Comment by rafaelstz** [comment]
Olá @fabisoccol 
Houve uma atualização á pouco tempo que causou alguns bugs como esse, provavelmente há algum trecho errado no código causando isso. Não vou conseguir te dizer com exatidão como corrigir, por não atualizar para essa nova versão, recomendo voltar commits e para ter uma versão desatualizada.

**Comment by fabisoccol** [comment]
Oi @rafaelstz , vou instalar a OSC 4 então! Muito obrigada! :-)

**Comment by rafaelstz** [comment]
Entre o OSC 4 e OSC 6 eu usaria o 6 mas voltando versão no git mesmo.

**Comment by fabisoccol** [comment]
@rafaelstz , procurei aqui no Git os arquivos antigos, mas não achei!

Procurei mais ainda também no Google sobre estes erro que está dando e muitos sites indicam conflito entre jQuery e o Javascript.

Seria possível isso? Onde encontro os arquivos antigos aqui no Git?

**Comment by rafaelstz** [comment]
Quando fizer o clone do repositório para sua máquina, basta executar:
```
git revert HEAD~1
```

**Comment by fabisoccol** [comment]
Oi @rafaelstz , infelizmente nem uma versão anterior resolveu o problema!

Alguém mais poderia me salvar??? :-(

**Comment by isaaclopes** [comment]
ola ve se ajuda
https://github.com/deivisonarthur/OSC-Magento-Brasil-6-Pro/issues/112#issuecomment-98880610

**Comment by fabisoccol** [comment]
Oi @isaaclopes , infelizmente já tinha tentado isso também. Veja só:

![image](https://cloud.githubusercontent.com/assets/8919031/11154474/b5cbb8ba-8a26-11e5-99f4-ba595e22e172.png)

O erro que está dando é:
<input type="text" id="billing:region" name="billing[region]" value=""  title="Estado" class="input-text 
Fatal error: Call to undefined method Mage_Customer_Helper_Address::getAttributeValidationClass() in /storage/6/64/c2/cozinhandoogalo/public_html/app/design/frontend/base/default/template/onestepcheckout/onestep/form/address/billing.phtml on line 184

A única coisa que me pareceu estranha é que eu não tenho uma opção de habilitar estado conforme indicado na instalação:

B - Habilite o Estado como obrigatório:

B1 - Visite a página: Admin : Sistema > Configuração "Aba Geral " > Opção de estado "Estado é necessário para" >

Alguém me ajuda, please! #desesperada

**Comment by fabisoccol** [comment]
@rafaelstz e @isaaclopes , vocês poderiam indicar um desenvolvedor que faria este freela para mim? Estou com muitos outros detalhes de design da loja e gostaria que alguém com mais conhecimento pudesse finalizar a instalação pra mim!

Seria possível? :-(

**Comment by rafaelstz** [comment]
@fabisoccol Não estou pegando freela pela correria, verifiquei com alguns colegas e todos também não estão pegando freela, caso saiba de alguém peço para entrar em contato com você.

**Comment by rkb81** [comment]
@fabisoccol para serviços com Magento, só me escrever [rick@studioboz.com.br](rick@studioboz.com.br)

**Comment by fabisoccol** [comment]
@rkb81 , por incrível que pareça, a dica do @isaaclopes funcionou. Comentei a linha 184 e funcionou corretamente.

Muito esquisito, mas foi!

Muito muito muito obrigada pelo empenho de todos vocês em me ajudarem.

@rkb81 , seu contato está guardado! :-)
Obrigada a todos.
