### ISSUE TITLE
Não calcula o frete de primeira, erro "Por favor, corrija o CEP digitado, ele não está correto."

### ISSUE THREAD

**Issue by rebecapf** [deivisonarthur/OSC-Magento-Brasil-6-Pro#180]
Olá,
Aconteceu a seguinte situação:
- Realizei um cadastro de cliente novo
- Cadastrei um novo endereço e finalizei o pedido, blz!
Deu tudo certo até aí. 
Então fui realizar um novo pedido, já com o endereço cadastrado. Quando chegou no OSC, o endereço que estava no drop down já era o correto e o mesmo da compra anterior, mas apareceu a mensagem "Por favor, corrija o CEP digitado, ele não está correto." no bloco do frete. O que eu fiz: 
- Selecionei Novo endereço no drop down
- Depois selecionei o endereço que estava antes... aí o frete calculou!

O problema é, meu cliente não vai adivinhar isso.. o que eu posso fazer pra arrumar???

Desde já, agradeço!

**Comment by rafaelstz** [comment]
Aparece algo no console?
