### ISSUE TITLE
Validação de e-mail e CPF em Cadastro usando SSL (HTTPS) no frontend

### ISSUE THREAD

**Issue by GustavoSartori** [deivisonarthur/OSC-Magento-Brasil-6-Pro#183]
Olá a todos e feliz ano novo!

Estou utilizando Magento 1.9.2.2 e OSC 6 PRO atualizado em um servidor GoDaddy com SSL no frontend.

Quando um cliente vai realizar um cadastro, a validação de E-mail e CPF simplesmente não funcionado. O erro é bem semelhante ao descrito no issue #49, mas a solução não parece resolver o meu problema.

Se eu desativo o HTTPS no frontend consigo realizar meu cadastro normalmente (apensar do autocompletar retornar 404 no console, mas este é o menor dos meus problemas). Mas se tento realizar um cadastro com o HTTPS ativado, independente do endereço de e-mail ou CPF que informo, a validação retorna como se os campos estivessem vazios ou incorretos.

Alguém tem alguma dica?

Abraços!

**Comment by fffcion** [comment]
Opa

me parece que no base/default/template/onestepcheckout/persistent/customer/form/register.phtml
linha 200
        var urlBase = "<?php echo Mage::getBaseUrl(); ?>";

mudei pra <?php echo Mage::getUrl('',array('_secure'=>true); ?>"; e o erro parou, mas nao submete o cliente!!! volta pro formulario em branco! alguma pista???

**Comment by perrera** [comment]
Ola amigo, eu estava exatamente com o mesmo problema. Depois que eu instalei o certificado SSL os usuarios nao conseguiam fazer o registro no site.
O que eu fiz foi alterar o:
app\design\frontend\base\default\template\onestepcheckout\onestep\form\address\billing.phtml

Alterei cada variavel conforme a seguir:
var url = 'https://seudominio.com.br/onestepcheckout/ajax/check_email/';
var url = 'https://seudominio.com.br/onestepcheckout/ajax/check_taxvat/'


app\design\frontend\base\default\template\onestepcheckout\persistent\customer\form\register.phtml

Alterei cada variavel conforme a seguir:
var url = 'https://seudominio.com.br/onestepcheckout/ajax/check_email/';
var url = 'https://seudominio.com.br/onestepcheckout/ajax/check_taxvat/'


Não é o ideal, mas foi o único jeito que funcionou.
Se alguém tiver uma solução mais adequada.

**Comment by GustavoSartori** [comment]
Minha solução foi um pouco mais simples.
Nas configurações do Magento deixei tanto o 'base url' quanto o 'secure base url' com **https**://meudominio... Com isso também tive o benefício de deixar todo o frontend da loja sob o ssl. Deixando o base sem https, além de gerar um monte de erros de permissão, estava dando uns 404 em algumas imagens.

**Comment by apzeiro** [comment]
@GustavoSartori você removeu o {{unsecure_base_url}} e {{secure_base_url}} e colocou manualmente seu domínio? Foi isso?
Eu estava com esse mesmo problema e tentei apenas colocar httpS no campo URL Base mas não funcionou, o problema continuava.

Eu tive que fazer manualmente como o @perrera indicou. Daí resolveu.
Mas queria entender melhor como você fez porque seria uma saída menos dolorosa do que alterar o código.
Se puder, me explique um pouco melhor por favor. Obrigado.
