### ISSUE TITLE
OSC 6 - "" is a required value.

### ISSUE THREAD

**Issue by EduardoPrezzi** [deivisonarthur/OSC-Magento-Brasil-6-Pro#189]
Bom dia,
 Estou com um problema no OneStepCheckout 6, onde mesmo preenchendo todos os campos, quando clico em 'Finalizar Pedido', me retorno um alert com (""is a required value). 
 
Vi que ele é puxado através da function onComplete, porém não consegui descobrir que campo não está preenchido.

Estou usando um template (default/meutema) 
Alguma luz?

**Comment by rafaelstz** [comment]
Conseguiu resolver @EduardoPrezzi , como?

**Comment by EduardoPrezzi** [comment]
Olá,
 Sim, resolvemos. 
De fato não havia nada de errado com o módulo e sim com um campo que puxava juntamente com o backup da loja Magento antiga. Existia um campo 'bairro' como obrigatório, porém na nova loja não existia e não mostrava em lugar algum.
A solução foi ir no BD e setar como opcional.

Agradeço.

**Comment by roneclay** [comment]
@EduardoPrezzi valeu, muito obrigado! Aqui funcionou perfeitamente. Temos uma loja que migrou de versão e na versão antiga tinha resquícios de módulos antigos requerendo estas e outras informações no checkout. Fizemos como você indicou e salvou nosso dia. Obrigado.

**Comment by EduardoPrezzi** [comment]
Show! =D

Atenciosamente,


*Eduardo Prezzi*
*54 9207.3718*
*copartner.com.br <http://www.copartner.com.br>*
facebook.com/copartner
<http://www.copartner.com.br>

Em 24 de fevereiro de 2016 13:02, Ronne Clay Santos <
notifications@github.com> escreveu:
