### ISSUE TITLE
'Finalizar Pedido Disabled' após mudar frete ou forma de pagamento

### ISSUE THREAD

**Issue by cfgalvani** [deivisonarthur/OSC-Magento-Brasil-6-Pro#197]
Título diz tudo.. Após alterar o Frete ou a Forma de Pagamento o botão de checkout fica Disabled e não volta.. Alguma dica?

www.vedaeprotege.com.br

**Comment by Chicodarave** [comment]
Também estou com esse problema :(

**Comment by apzeiro** [comment]
Alguma solução?

**Comment by cfgalvani** [comment]
Está longe de ser uma solução mas resolveu meu problema.. O que fiz foi renomear o arquivo onestep.phtml do path app/design/frontend/rwd/<default ou o seu tema>/tempalte/onestepcheckout
Fazendo isso ele vai pegar o onestep.phtml do app/design/frontend/base/default/template/onestepcheckout que, pra mim, funcionou perfeitamente..

**Comment by apzeiro** [comment]
@cfgalvani fiz esse teste e realmente funciona no tema RWD. Estou problemas maiores no tema que estou usando, que não é o RWD.

Eu fico pensando quem faz um módulo achando que as pessoas irão usar o default????

**Comment by Chicodarave** [comment]
Apaguei o arquivo indicado por cfgalvani e o botão "Finalizar Pedido" funcionou.
Estou com uma instalação limpa do Magento 1.9.2.2 em localhost.
Está no root, instalei SOMENTE o OSC 6 e a tradução do MarioSam.
O tema é o padrão do Magento (RWD).
Não fiz nenhuma modificação.
A validação de CPF e e-mail passou sem nenhuma alteração, o problema do botão "Finalizar Pedido" aparentemente resolveu com esse procedimento, porém tá dando problema no CEP.

**Comment by cfgalvani** [comment]
@apzeiro, o módulo não está perfeito mas com certeza é a melhor solução! Cabe a nós também ajudarmos para melhorar o osc cada vez mais!
@Chicodarave, o que acontece com o CEP?

**Comment by Chicodarave** [comment]
@cfgalvani, ao completar o CEP ele deveria preencher o endereço, porém fica carregando, não sai disso nem preenche o endereço.
Obrigado pela atenção.

**Comment by cfgalvani** [comment]
Copia a pasta skin/frontend/base/default/onestepcheckout/js para skin/frontend/rwd/<default ou seu tema>/onestepcheckout e ve se funciona @Chicodarave

**Comment by Chicodarave** [comment]
@cfgalvani, infelizmente não fez diferença :(
Tem que fazer algo mais? Liberei cache do Magento, cache armazenado e cache JS.

**Comment by apzeiro** [comment]
@Chicodarave testou em mais de um navegador?
Verifica como está a requisição do ajax.

É obvio @cfgalvani , mas um software numa versão 6 a gente presume que já "saiu da papinha" faz tempo. Ajudar é o motivo de estarmos aqui.

**Comment by apzeiro** [comment]
@Chicodarave , isso aqui https://github.com/diegosm/OSC-Magento-Brasil-6-Pro/commit/36587a5a444c04c7e89811ba3887e4cb78f9f52d vc já tentou ne?

**Comment by Chicodarave** [comment]
@apzeiro, não sei como faz essa verificação.
E o outro procedimento não fiz pois meu problema não está na validação do CPF e do E-mail, e minha loja está na raiz.
"Resolve problemas no ajax, caso a loja não esteja instalada na raiz."

**Comment by cfgalvani** [comment]
@Chicodarave.. tenta mais uma coisa.. no lugar do <?=Mage::getBaseUrl();?>, troca pela url da sua loja mesmo.. se for https já coloca com https.. eu estava com problema pra validar o email e tive que fazer essa troca do <?=Mage::getBaseUrl();?> pela url segura..

**Comment by Chicodarave** [comment]
@cfgalvani, em qual arquivo?
O meu está em localhost, como colocaria dai? http://127.0.0.1/ ?

**Comment by cfgalvani** [comment]
no app/design/frontend/base/default/template/onestepcheckout/onestep.phtml
tenta de tudo.. nunca desenvolvi em localhost..

**Comment by apzeiro** [comment]
@Chicodarave o fato de rodar em localhost pode si gerar diversos problemas.
Eu mesmo nunca consegui rodar bem o magento num WAMP (Windows). O máximo que eu fiz foi rodar num linux da rede.
Ao invés de usar localhost ou 127.0.0.1, é mais interessante simular um domínio. Para isso vá no seu arquivo de hosts ou vhosts e coloque um domínio tipo magentol.local apontado pra 127.0.0.1
Daí vc faz tudo usando esse domínio falso.

**Comment by Chicodarave** [comment]
@apzeiro, acho que entendi sua ideia, mas fui olhar lá no hosts e localhost já aponta para 127.0.0.1, então usar localhost daria na mesma, e ao navegar para localhost ele troca por 127.0.0.1, então acho que tudo acaba dando na mesma.
De qualquer forma vou tentar, mas acho que preciso reinstalar o Magento, certo?

Outra coisa, rfbastos pediu para eu fazer o procedimento do CEP com o console aberto, o erro que aparece é este:
http://127.0.0.1/customer/address/editajax/busca_cep?cep=88103970&_=1456471482595 404 (Not Found)
Isso com o código original.
Eu não entendo muito, mas na minha burrice ficou claro que há um sério erro de caminho, minha impressão é que ele tentou obter a raiz do site removendo X caracteres do final da URL atual (que é http://127.0.0.1/customer/address/edit/id/1/") então adicionou "ajax/.....".
O que estou estranhando é que não há pasta "ajax" nem "onestepcheckout" na raiz do Magento.
Qual seria o caminho correto disso que "ele" quer fazer?
Estou sem saber o que fazer aqui.

Obrigado pela atenção.
Um abraço.
