### ISSUE TITLE
Logado como PJ, novo endereço no chekout vem com campo PF...

### ISSUE THREAD

**Issue by NelsonJunioon** [deivisonarthur/OSC-Magento-Brasil-6-Pro#204]
Pessoal, o que acontece é seguinte!

Ao eu finalizei a primeira compra como PJ e foi tudo certo.
Mas o que acontece é que na segunda compra quando você esta logado como PJ e seleciona a opção de novo endereço, ele traz os campo como se fosse PF (Nome, Sobrenome), não deixa como PJ (Razão Social, Nome Fantasia)...

Vejam na imagem o que estou falando!

![d7fa514e-e23c-11e5-89fa-cca204710fa7](https://cloud.githubusercontent.com/assets/8427757/13573877/84fc677c-e460-11e5-9bce-7add2ee4b465.png)

Podem Ajudar?

**Comment by isaaclopes** [comment]
https://github.com/deivisonarthur/OSC-Magento-Brasil-6-Pro/issues/78
