### ISSUE TITLE
Tipo Pessoa não aparece

### ISSUE THREAD

**Issue by Alecostantini** [deivisonarthur/OSC-Magento-Brasil-6-Pro#21]
Boa tarde,

Estamos testando o módulo e na página de cadastro o campo Tipo Pessoal não aparece e também não aparece nenhuma opção do backend para habilitá-lo.

Quando clicamos em editar as informações do usuário, temos o seguindo erro:
a:5:{i:0;s:52:"Source model "" not found for attribute "tipopessoa"";i:1;s:4123:"#0 /Applications/XAMPP/xamppfiles/htdocs/magento/app/code/core/Mage/Eav/Model/Entity/Attribute/Abstract.php(387): Mage::exception('Mage_Eav', 'Source model ""...')

Poderiam ajudar?

Obrigado.

**Comment by filipe-cs** [comment]
Resolveu isso aí?

**Comment by fernandoosp** [comment]
To com esse problema, alguem conseguil resolver ?

**Comment by filiprimo** [comment]
https://github.com/deivisonarthur/OSC-Magento-Brasil-6-Pro/issues/67#issuecomment-72124372
