### ISSUE TITLE
Posicionamento radio buton pessoa física e pessoa jurídica

### ISSUE THREAD

**Issue by diegohpena** [deivisonarthur/OSC-Magento-Brasil-6-Pro#253]
Olá, no meu site a seleção de pessoa física e jurídica estava confusa.
Estava escrito:
Pessoa Física Pessoa Jurídica Radio1 Radio2

Onde Radio1 e 2 são os botões para o cliente selecionar, estava tudo um de atrás do outro.

Tentei fazer a solução indicada por outro colega colocando um < br > < / br > na linha 16 do arquivo billing.phtml mas não funcionou.

Mais alguém está/esteve com o mesmo problema e conseguiu arrumar?

Abraço

Ps: o site em questão é www. cristhishoes. com. br

**Comment by LuizSantos22** [comment]
@diegohpena Como você conseguiu resolver esse problema?
