### ISSUE TITLE
Opção para salvar novo endereço no OSC não salva o nome da cidade

### ISSUE THREAD

**Issue by PhoenixJam** [deivisonarthur/OSC-Magento-Brasil-6-Pro#262]
Olá, estou tendo um problema no salvamento de um novo endereço no meu OneStepCheckout.

Todos os dados são salvos no banco de dados, a tabela sales_flat_order_address tem esses novos dados da forma que eu quero, incluindo a cidade, mas quando eu uso a função getAddressesHtmlSelect a cidade não é trazida, resultando em um select com os endereços mas um espaço vazio entre virgulas aonde deveria estar a cidade. Quando o usuário tenta usar esse endereço, um alerta js aparece pra ele falando que '"Cidade" is a required value' e '"Cidade" length must be equal or greater than 1 characters.'

O problema parece estar relacionado com o salvamento do novo endereço na tabela customer_address_entity_varchar, já que os novos endereços salvos no checkout não preenchem a linha com a cidade nessa tabela enquanto os outros endereços já tem essa linha da cidade.

Fora do Checkout, se o usuário edita o endereço, essa linha do address_entity_varchar é preenchida e no Checkout o getAddressesHtmlSelect trás essa cidade para aquele endereço, que no select do template parece estar com todos os dados. No entanto, se tento usar esse endereço salvo para realizar o checkout, ele mostra um alerta de js parecido com o quando não tinha a cidade e me pede 'Please enter the state/province'.

**Comment by hansbonini** [comment]
Você está querendo puxar as cidades em um dropdown de acordo com o estado?

**Comment by PhoenixJam** [comment]
Oi Hans. Obrigado por participar. 
Felizmente, não era um problema relacionado com o OSC, era um outro modulo que um dev antigo não terminou de desenvolver e não desativou.
Esqueci de fechar essa issue.
[]'s
