### ISSUE TITLE
Erro 500 

### ISSUE THREAD

**Issue by jamersonlima** [deivisonarthur/OSC-Magento-Brasil-6-Pro#295]
Pessoal bom dia , 

Estou com magento 1.9 , instalei o OSC-Magento-Brasil-6-Pro via FTP ,  porém quando acesso sistema > configuração o mesmo apresenta erro 500 , só consigo acessar novamente se renomear o arquivo system.xml dentro de /public_html/app/code/community/Inovarti/Onestepcheckout/etc , alguem sabe como corrigor isso? Se renomeio o arquivo o OSC não aparece nas configurações. 

Desde já obrigado a todos !

**Comment by hansbonini** [comment]
Problema de permissões ou de .htaccess

**Comment by jamersonlima** [comment]
Boa noite ,

A unica solução foi remover todos os arquivos do OSC e tambem removi de outro checkout , depois subi novamente e funcionou normal :) 

Abraços
