### ISSUE TITLE
Nenhum CEP da cidade de Santa Bárbara do Oeste funciona

### ISSUE THREAD

**Issue by FelipeMartinin** [deivisonarthur/OSC-Magento-Brasil-6-Pro#315]
Notei que nenhum CEP da cidade de Santa Bárbada do Oeste está passando na validação de cep do módulo, segue um exemplo: 13457-160

**Comment by caunascimento** [comment]
@FelipeMartinin , veja se está habilitado o allow_url_fopen.

T+;

**Comment by FelipeMartinin** [comment]
@caunascimento Já foi resolvido. Primeiro foi identificado que qualquer endereço que o nome da cidade, bairro ou rua contém um " ' " (apóstrofo), dava erro. Depois foi identificado que o criador do módulo não encodou como json o resultado da api de busca de cep, se vinha algo que quebrasse o json como " ' " dava esse erro. Quem me ajudou nisso foi meu brother Felipe Marcos e caso queira detalhes pede um pull request pra ele: https://github.com/FelipeMarcos

**Comment by caunascimento** [comment]
@FelipeMartinin , o problema do meu era que nenhum CEP dava certo, e resolvi habilitando o allow_url_fopen . 

At-te;

**Comment by isaaclopes** [comment]
https://github.com/deivisonarthur/OSC-Magento-Brasil-6-Pro/commit/90d1b89323cee489d4bb15c5f16c7f06eda078c9
