### ISSUE TITLE
Busca por CEP não preenche os campos do endereço

### ISSUE THREAD

**Issue by fabianearaujo** [deivisonarthur/OSC-Magento-Brasil-6-Pro#316]
Olá pessoal, já olhei várias issues aqui, mas nenhuma das recomendações atenderam.
Eu preencho o CEP ele fica eternamente carregando. A forma de entrega aparece, ou seja, a API dos correios  #está funcionando corretamente.

O erro que aparece é o 524: /onestepcheckout/ajax/busca_cep?cep=28000400&_=1516644080331

**Comment by ymgomes** [comment]
Tente corrigir com a informação deste tópico. O sistema dos correios não está mais disponivel  https://github.com/deivisonarthur/OSC-Magento-Brasil-6-Pro/issues/310

**Comment by isaaclopes** [comment]
https://github.com/deivisonarthur/OSC-Magento-Brasil-6-Pro/commit/90d1b89323cee489d4bb15c5f16c7f06eda078c9
