### ISSUE TITLE
Erro Campo CPF/CNPJ e Telefones pelo celular

### ISSUE THREAD

**Issue by davicassis** [deivisonarthur/OSC-Magento-Brasil-6-Pro#325]
Ao acessar o formulário de cadastro ou chechout de uma semana para cá o campo cpf/cnpj se misturam e o cliente não consegue efetuar o cadastro com os dados corretos, O campo de telefone e celulares acrescentam inúmeros caracteres. Isso esta ocorrendo somente em alguns celulares. 

Alguém com o mesmo erro ou já passou por ele?

**Comment by phdiegues** [comment]
Boa tarde, já tive esse problema de auto completar números em celulares...

Adicione autocomplete="off"  e também coloque input type="tel" para que ele aceite apenas números no input do arquivo taxvat.html 
/app/design/frontend/base/default/template/customer/taxvat.phtml
na linha 29 aprox. ficando assim:

<div class="input-box">
    <input type="tel" autocomplete="off" id="<?php echo $this->getFieldId('taxvat')?>" name="<?php echo $this->getFieldName('taxvat')?>" value="<?php echo $this->escapeHtml($this->getTaxvat()) ?>" title="<?php echo $this->__('Tax/VAT number') ?>" class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('taxvat') ?>" <?php echo $this->getFieldParams() ?> />
</div>

tem o telefone tambem nos arquivos abaixo:

/public_html/app/design/frontend/default/shopper/template/onestepcheckout/customer/address/edit.phtml

frontend/default/shopper/template/onestepcheckout/onestep/form/address/billing.phtm

em phone, fax e postcode.

Abração.

**Comment by isaaclopes** [comment]
https://github.com/deivisonarthur/OSC-Magento-Brasil-6-Pro/commit/3d7d79ab6cc1bbd633e42ca59b207de90352779e
