### ISSUE TITLE
Bug ao buscar Cep - localidade com " ' "

### ISSUE THREAD

**Issue by JonathanCosta** [deivisonarthur/OSC-Magento-Brasil-6-Pro#328]
@isaaclopes ,  Existe um bug com esse novo código de cep:
exemplo, buscando pelo cep "13454275" o Viacep  retorna : 
`{
  "cep": "13454-275",
  "logradouro": "Rua Ametista",
  "complemento": "",
  "bairro": "Jardim São Fernando",
  "localidade": "Santa Bárbara D'Oeste",
  "uf": "SP",
  "unidade": "",
  "ibge": "3545803",
  "gia": "6063"
}`

a localidade quebra o retorno, fazendo o cep não preencher.
minha solução foi adicionar "addslashes"  parte do código para :

`$return = "var resultadoCEP = { 'uf' : '".addslashes($dados['uf'])."', 'cidade' : '".addslashes($dados['localidade'])."', 'bairro' : '".addslashes($dados['bairro'])."', 'tipo_logradouro' : '', 'logradouro' : '".$dados['logradouro']."', 'resultado' : '1', 'resultado_txt' : 'sucesso%20-%20cep%20completo' }";`  

#320 
#315

**Comment by isaaclopes** [comment]
ola @JonathanCosta Obrigado feito a alteração
