### ISSUE TITLE
Quando um cliente faz o cadastro na hora do checkou, ele não direciona o cliente para a forma de pagamento.

### ISSUE THREAD

**Issue by gabrielmazaia** [deivisonarthur/OSC-Magento-Brasil-6-Pro#329]
Boa tarde, estou enfrentando alguns problemas com o OSC, quando o meu cliente faz a conta dele através da página de Checkout, ele cria a conta tudo corretamente, mas não é direcionado para a página do pagamento. 

No caso estou utilizando o módulo do PagSeguro do Ricardo Martins em conjunto. 
E quando seleciono a opção boleto e clico para criar uma conta ao finalizar a compra, ele direciona o meu usuário para a home da loja. Quando isso acontece, não aparecem log's, ele apenas faz um redirecionamento para  home, como se ela fosse a página de sucesso.

Se eu faço o mesmo processo estando logado não tenho problemas.
Temporariamente eu desativei o cadastro no checkout, para que o cliente esteja logado pra efetuar a compra.

Gostaria de saber se mais alguém já teve este problema e ou o que pode estar ocasionando... Já verifiquei os logs de erros e não consta nenhum erro, também verifiquei nos logs do PagSeguro e não consta problemas.

Estou usando o Magento 1.9.2.4.
E estou usando a ultima versão do OSC e do PagSeguro.

**Comment by fernandoperigolo** [comment]
Por acaso você tem o patch SUPEE-10570 instalado na loja? Aconteceu exatamente isso comigo, você precisa instalar o patch SUPEE-10570 V2 e não instalar o SUPEE-10752 por que ele sobreescreve o SUPEE-10752 V2.

Agora saiu o SUPEE-10888 e eu ainda não testei pra ver como ficou.

**Comment by gabrielmazaia** [comment]
Muito Obrigado Fernando, acredito que tenha sido isto mesmo!
