### ISSUE TITLE
RG não aparece no Painel (backend)

### ISSUE THREAD

**Issue by luisgennari** [deivisonarthur/OSC-Magento-Brasil-6-Pro#53]
Instalei o modulo no magento 1.9 e está quase 100%. Estou tendo o seguinte problema:
O Rg é de preenchimento obrigatório. O cliente cadastra mas o RG não aparece no backend.
2) O cliente se cadastra como pessoa física, mas no backend tem que selecionar manualmente o tipo para o cliente.

No console não tem nenhum erro. Qual será o problema?

**Comment by luisgennari** [comment]
Oi Rafael,
Estou utilizando o template padrão RWD. Os arquivos estão em frontend/rwd/default/template/onestepcheckout/onestep.phtml

**Comment by luisgennari** [comment]
Será que ao menos gravou o RG no banco de dados? Alguém sabe qual tabela do banco devo consultar para saber se foi gravado?

**Comment by luisgennari** [comment]
Eu estava testando o módulo em uma instalação magento completa com bando de dados incluído. Hoje testei em uma instalação do magento limpa, mas esse problema no RG continua. 

• O RG não aparece na conta do cliente (customer/account/edit/)
• O RG não aparece no painel administrativo

No restante, o módulo funciona perfeitamente.

Alguém tem uma luz?

**Comment by isaaclopes** [comment]
Ola tenta usar esse modulo para *verificar os campos de cliente.
https://github.com/deivisonarthur/OSC-Magento-Brasil-6-Pro/issues/31#issuecomment-63545739

seu OSC esta atualizado para ultima versão?
<i>PS. o RG = IE (Inscrição municipal)</i>

**Comment by luisgennari** [comment]
Olá Lopes,
Não entendi o que você quis dizer. Verificar os campos de cliente? Para que isso?

O Campo RG aparece durante o cadastro no checkout. Mesmo preenchendo esse campo, não aparece na conta do cliente e não aparece no painel administrativo.

Com relação ao OSC, baixe diretamente aqui no Github a uma semana atrás.

**Comment by isaaclopes** [comment]
Ola esse modulo que passeei ele mostra os campos criados para o cliente.
la voce possível saber se o campo IE esta criado e se está visível para o
admin/cliente/edição e etc

Em 11 de janeiro de 2015 22:09, luisgennari <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> escreveu:

> Olá Lopes,
> Não entendi o que você quis dizer. Verificar os campos de cliente? Para
> que isso?
>
> O Campo RG aparece durante o cadastro no checkout. Mesmo preenchendo esse
> campo, não aparece na conta do cliente e não aparece no painel
> administrativo.
>
> Com relação ao OSC, baixe diretamente aqui no Github a uma semana atrás.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/deivisonarthur/OSC-Magento-Brasil-6-Pro/issues/53#issuecomment-69518981>
> .
>



-- 

*Isaac Lopes dos Santos*

[image: Descrição: iphone icon]

*+55 (11) 97164-4721*

[image: Descrição: envelope icon]

*contato@isaaclopes.com.br
<javascript:_e(%7B%7D,'cvml','contato@isaaclopes.com.br');>*

[image: Descrição: share icon]

*http://www.linkedin.com/in/isaaclopes
<http://www.linkedin.com/in/isaaclopes>*

[image: Descrição: mouse icon]

*http://isaaclopes.com.br <http://isaaclopes.com.br/>*


-- 

*Isaac Lopes dos Santos*

[image: Descrição: iphone icon]

*+55 (11) 97164-4721*

[image: Descrição: envelope icon]

*contato@isaaclopes.com.br <contato@isaaclopes.com.br>*

[image: Descrição: share icon]

*http://www.linkedin.com/in/isaaclopes
<http://www.linkedin.com/in/isaaclopes>*

[image: Descrição: mouse icon]

*http://isaaclopes.com.br <http://isaaclopes.com.br/>*

**Comment by luisgennari** [comment]
Olá Lopes,
Os campos existem. Está ocorrendo um problema na gravação dos dados (RG /Inscr. Estadual). 

Fazendo mais alguns testes, identifiquei o seguinte:

1) Quando me cadastro através do link "cadastrar" (/customer/account/create/)
• O RG ou Inscrição estadual ficam gravados no painel administrativo.
• Não aparece na conta do cliente.

2) Quando me cadastro diretamente no OSC ao finalizar um pedido
• O RG ou inscrição estadual não grava no painel administrativo.
• Não aparece na conta do cliente.

**Comment by isaaclopes** [comment]
Ola @luisgennari  

1) 
Quando me cadastro através do link "cadastrar" (/customer/account/create/)
• 
• Não aparece na conta do cliente.
---> voce pode estar com um template que esta sobrescrevendo o arquivo;
---> https://github.com/deivisonarthur/OSC-Magento-Brasil-6-Pro/blob/master/app/design/frontend/base/default/template/onestepcheckout/customer/address/edit.phtml

2) Quando me cadastro diretamente no OSC ao finalizar um pedido
• O RG ou inscrição estadual não grava no painel administrativo.
---> acabei de subir um fix;
---> https://github.com/deivisonarthur/OSC-Magento-Brasil-6-Pro/commit/397ec88c75d628051e4b50cc30f81273dbabea6a
• Não aparece na conta do cliente.

**Comment by luisgennari** [comment]
Boa noite Lopes,
Muito obrigado pelo Fix! Fiz a atualização e agora está funcionando perfeitamente.

Grande abraço.

**Comment by luisgennari** [comment]
Lopes,

Vou ter que reabrir essa issue. Alguns problemas foram corrigidos, mas apareceram outros.

Problemas resolvidos:
• Após a atualização do módulo, entrei no painel administrativo e o RG estava aparecendo e gravado!
• o tipo de pessoa estava gravado!

Problema que surgiu após a atualização:
• Ao tentar criar uma nova conta em customer/account/create/, não aparece o campo cpf / Rg e não aparece cnpj / IE para pessoa jurídica.

No console aparece o seguinte erro:
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
(/costumer/account/create)

OBS: Utilizo o layout WRD padrão do magento 1.9.1

**Comment by isaaclopes** [comment]
@luisgennari  ja foi ajustado
https://github.com/deivisonarthur/OSC-Magento-Brasil-6-Pro/commit/f294158eccc5fdd0424fa5b52d1ee60478af9c8d

**Comment by luisgennari** [comment]
Obrigado Lopes,
Tudo funcionando 100% agora!

Obrigado pela contribuição.
