### ISSUE TITLE
Ocultar campos "Empresa" e "Número VAT" para pessoa física.

### ISSUE THREAD

**Issue by luisgennari** [deivisonarthur/OSC-Magento-Brasil-6-Pro#54]
Pessoal,

Qual é o procedimento para ocultar os campos "Empresa" e "Número VAT" quando a pessoa opta pelo cadastro de "Pessoa Física"?

**Comment by luisgennari** [comment]
Pessoal,

Para desabilitar o campo "empresa", basta ir no backend em:

Sistema > Configuração > One Step Checkout > Incluir / excluir Campos

e basta desabilitar.

Só não descobri ainda como excluir o "número VAT".

**Comment by luisgennari** [comment]
Pessoal,

Para remover o campo "numero Vat" do checkout, deve ser feito um procedimento manualmente:
1) editar o arquivo app/design/frontend/base/default/template/onestepcheckout/onestep/form/address/billing.phtml

2) Na linha 159, mudar de class="wide" para class="no-display"

Dessa forma, o campo "Número VAT" não aparece mais no checkout.

**Comment by Chicodarave** [comment]
Obrigado!

**Comment by alfredocosta** [comment]
Muito bom, obrigado!!

**Comment by camaleonozzy** [comment]
Obrigado!!

**Comment by aquere** [comment]
Ele ainda aparece no Mobile, teria alguma maneira de tirar?

**Comment by rafaeldesio** [comment]
@aquere bom dia, tudo bem?
conseguiu resolver quanto ao mobile?
Obrigado

Rafael
