### ISSUE TITLE
Erro na Instalação

### ISSUE THREAD

**Issue by djgoulaer** [deivisonarthur/OSC-Magento-Brasil-6-Pro#60]
Instalei o módulo manualmente, em um servidor NGINX com magento 1.9.0.1.
No entanto está dando erro fatal no servidor. Olhando os logs encontrei isso:

`FastCGI sent in stderr: "PHP message: PHP Fatal error:  Class 'Inovarti_Onestepcheckout_Helper_Data' not found in /usr/share...`

Inicialmente achei que poderia ser permissão, então resetei as permissões dos arquivos da loja:

`$ find . -type f -exec chmod 644 {} \;`
`$ find . -type d -exec chmod 755 {} \;`
`$chmod -R o+w media var`
`$chmod o+w app/etc`

Depois, só pra ter certeza, verifiquei nos diretórios do módulo pra ver se o arquivo estava realmente lá :), e estava rsrsr

Mesmo assim não obtive sucesso.

Alguém tem alguma idéia de como resolver isso?

**Comment by rafaelstz** [comment]
mas o Magento puro funciona no seu Server?

**Comment by djgoulaer** [comment]
Funciona tranquilo.
Em 16/01/2015 18:32, "Rafael Corrêa Gomes" <notifications@github.com>
escreveu:

**Comment by deniscsz** [comment]
Me parece que está faltando algum arquivo ou o mesmo esta na pasta
incorreta. Ele não está achando a classe do helper.
Em 16/01/2015 19:27, "djgoulaer" <notifications@github.com> escreveu:

**Comment by isaaclopes** [comment]
@djgoulaer  verifica dentro de app/etc/modulo nao existe outra OSC instalada se tiver desativa dexa apenas a versão Inovarti_Onestepcheckout

**Comment by djgoulaer** [comment]
Nenhuma há nenhuma.
:(
Em 17/01/2015 14:53, "Isaac Lopes" <notifications@github.com> escreveu:

**Comment by isaaclopes** [comment]
@djgoulaer me adiciona no skype e me chama quando puder isaac.lopes.santos

**Comment by djgoulaer** [comment]
Pessoal, reinstalei tudo do zero e funcionou perfeitamente.
Não consegui identificar com exatidão o que era, mas suspeito que poderia ser o compilador que estava ativado ( que eu só lembrei depois que ja tinha refeito tudo).

Agradeço imensamente aos que me ajudaram, @isaaclopes , @deniscsz , @rafaelstz
