### ISSUE TITLE
Adyen Pagamentos

### ISSUE THREAD

**Issue by rickbenetti** [deivisonarthur/OSC-Magento-Brasil-6-Pro#65]
Pessoal,
estou  com um problema muito sério, instalei o OSC pro 6, o tipo de pessoa não funciona salva todos como  Pessoa física, mas é o menor dos problemas, instalei e configurei o módulo da Adyen tudo certinho inclusive uma [correção](https://github.com/adyenpayments/magento/issues/179#issuecomment-71467397) que eles apontaram pra cartão de crédito pra resolver, mesmo assim não consigo testar e aprovar o pagamento eles falaram que é problema no checkout que não envia os dados encriptados, não sei mais o que fazer alguém já passou por isso?

Quem quiser testar a loja está em http://minori.jobboz.com.br os [cartões pra testes](https://www.adyen.com/home/support/knowledgebase/implementation-articles.html?article=kb_imp_17) da Adyen

**Comment by rafaelstz** [comment]
Ontem apareceu o mesmo problema com PagSeguro transparente, o savePaymentMethod retorna erro. Com tema RWD com OSC 6 tudo limpo funcionou após alguns testes, estou identificando o erro, testa com Adyen também, pois pode ser estrutura.

**Comment by isaaclopes** [comment]
ola @rafaelstz mas vc diz um erro no methodo ou erro na estrutura do gateway?

**Comment by rafaelstz** [comment]
Não dediquei muito tempo para verificar ontem, hoje irei debugar mais, mas pelo que vi aparenta ser no método.

**Comment by fernandoperigolo** [comment]
Você ativou a opção "Enable Client-Side Encryption" no módulo da Adyen?

**Comment by rickbenetti** [comment]
A opção Enable Client-Side Encryption está ativa e ainda estou usando somente a chave de testes, não a chave de live, pois ainda não é ambiente de produção, ou tenho que usar as duas?

**Comment by fernandoperigolo** [comment]
Você pode usar só a teste. Só depois de tudo homologado você recebe a chave de live. Pode usar só a de teste por enquanto sem problema.

Perguntei por que normalmente, quando receberemos este erro é por que os dados do cartão são inválidos. Ou seja, está chegando certinho na Adyen e retornando.
No seu caso, como é ambiente de teste, não era pra dar este erro se você estiver usando os dados de teste que você mesmo linkou.

Você já verificou em https://ca-test.adyen.com/ca/ca/login.shtml se a tentativa aparece na lista de compras?

Já tentou desativar o "Enable Client-Side Encryption"? Ele não é obrigatório para funcionar. Nem em produção.

Eu tenho uma loja Magento com OSC6 e Adyen funcionando. Subiu semana passada e funciona 100%.

**Comment by rickbenetti** [comment]
Muito estranho, mas realmente funcionou.

Obrigado @fernandoperigolo

**Comment by fernandoperigolo** [comment]
@rickbenetti olha ai, https://github.com/adyenpayments/magento/commit/c691e89184b5016d37140f33d377680559cce883

Um dos projetos grandes que eu trabalho usa o OSC6 + Adyen, os cara ajudam muito. Agora temos suporte.

**Comment by rickbenetti** [comment]
@fernandoperigolo mesmo aplicando isso e outras correções não funciona, por isso estamos retirando a adyen por que estamos há 3 semanas que não evoluimos com o OSC6 + Adyen.
