### ISSUE TITLE
OSC estilizada

### ISSUE THREAD

**Issue by mholperin** [deivisonarthur/OSC-Magento-Brasil-6-Pro#66]
Olá,

Gostaria de saber como eu mudo para essas telas Estilizadas 1, 2 ou 3, que tem nas imagens de demo.
E parabéns pelo modulo!!

Obrigado!

**Comment by rickbenetti** [comment]
Olá @mholperin terá que fazer as alterações no css do OSC, se não tiver conhecimento para tal, recomendo contratar alguém que entenda pra lhe ajudar com tal tarefa, pois pra quem codifica em CSS é fácil, mas o caminho é este:

Duplicar o arquivo:
```
skin/frontend/base/default/onestepcheckout/css/onestepcheckout.css
```
E salvar o arquivo em:
```
skin/frontend/[seutema/pacote]/default/onestepcheckout/css/onestepcheckout.css
```

E aí fazer as alterações neste CSS conforme desejar, não existe tema de CSS pronto pra esses modelos.

**Comment by mholperin** [comment]
saquei...pensei q como tinha as imgs, vcs ja tivessem feito essas telas! Mas blz..vou mexer no css!! valeeeeu!
