### ISSUE TITLE
ReferenceError na Consulta de CEP

### ISSUE THREAD

**Issue by luisgennari** [deivisonarthur/OSC-Magento-Brasil-6-Pro#68]
Pessoal,

O módulo estava rodando 100% na versão 1.9.1,tema (RWD) padrão. No entanto, vi um tutorial para aumentar performance do magento sugerindo ativar alguns módulos do apache. Agora no console aparece o erro abaixo e não retorna nenhum resultado na consulta do CEP. Já retornei os módulos padrão do apache voltei a comentar as linhas referentes ao módulo no .htaccess mas o erro continua.

[Error] ReferenceError: Can't find variable: resultadoCEP
	(função anônima) (validation.js, line 164)
	k (jquery.min.js, line 2)
	fireWith (jquery.min.js, line 2)
	y (jquery.min.js, line 2)
	d (jquery.min.js, line 2)

Alguém consegue me ajudar com isso?

**Comment by rafaelstz** [comment]
Tenta colocar os arquivos do módulo por cima novamente zerados, tenta reiniciar o apache também.

**Comment by RogerioKleinkauf** [comment]
A URL de consulta do cep está fora do ar.

http://cep.republicavirtual.com.br/web_cep.php

http://prntscr.com/60y19d

**Comment by luisgennari** [comment]
Olá rogério,
então você acha que não tem nada haver com as modificações do apache? O problema se deve pelo fato da URL de consulta estar fora do ar?

**Comment by luisgennari** [comment]
Rafael,
Eu já havia removido o apache e instalei todo novamente mas o erro persistia. Depois da dica do Rogério fiquei monitorando e ele tem razão, o problema era que a URL que faz consulta do CEP não estava respondendo. Agora já voltou ao normal!

Obrigado aos dois, Rafael e Rogério pelas dicas. Agora está tudo normalizado novamente.

Sucesso a todos!

**Comment by rafaelstz** [comment]
Se quiser testar o sistema dos Correios via API (usando a mesma do módulo) pode usar esse App que desenvolvi para Chrome.
http://goo.gl/HC7l8u
