### ISSUE TITLE
Dúvidas sobre campo CPF (OSC4) e TAX VAT (OSC6)

### ISSUE THREAD

**Issue by GustavoSartori** [deivisonarthur/OSC-Magento-Brasil-6-Pro#71]
Olá galera, tudo bem? Tenho algumas dúvidas e acredito que vocês consigam sanar facilmente.

No ambiente de produção estou usando o OSC 4 configurado para utilizar o campo CPF/CNPJ no cadastro de cliente.

Num ambiente de teste estou configurando e customizando o OSC 6, mas notei que ao invés do campo CPF/CNPJ, o OSC 6 utiliza o campo padrão do Magento TAX VAT.

Minhas dúvidas: 
1. Como o sistema irá reagir com aqueles clientes que já tinham cadastro antes do upgrade de checkout? O Magento vai pedir que o usuário preencha o dado faltante? Em que momento?
2. No caso do cliente não recordar da senha o problema parece ser mais sério... Fiz um teste com um usuário admin que não tem este campo preenchido, mas o link de redefinição de senha já vem 'vencido' e com a mensagem "O Campo CPF ou CNPJ deve ser informado".
3. Considerando que as respostas anteriores sejam algo do tipo "não tem jeito", existe alguma forma de copiar (via BD) todos os dados dos campos CPF 'genérico' para os campos TAX VAT de seus respectivos cadastros?

Bom galera, agradeço desde já pelo apoio aqui, sempre muito rápido e eficaz!

**Comment by rafaelstz** [comment]
Não sei informar sobre a dúvida 1 e 2, mas caso realmente não houver jeito aconselho customizar o OSC6 para usar o campo CPF/CNPJ como está o seu atual OSC4.

**Comment by GustavoSartori** [comment]
Isso eu não saberia fazer... Pelo menos no OSC6 não existe esta opção no menu. Como poderia fazer essa alteração?

**Comment by rafaelstz** [comment]
Não sei te informar com exatidão os passos para fazer, pois nunca precisei fazer.

**Comment by isaaclopes** [comment]
ola @GustavoSartori veja se a informação abaixo ajuda.
1 - cria um arquivo "atualiza_customer.php" na raiz do seu magento;
2 - cola o script  https://gist.github.com/isaaclopes/d86817d9747d703e116d
3 - executa no seu browser
 
PS. Precisa alterar os id com a informação do seu banco!
