### ISSUE TITLE
Compressão de Scripts

### ISSUE THREAD

**Issue by rickbenetti** [deivisonarthur/OSC-Magento-Brasil-6-Pro#74]
Ativei a função do Magento para unificar e compactar os scripts e CSS, pra CSS não tive problemas, porém pra Scripts somente o OSC Pro 6 causou erro:

Uncaught ReferenceError: OnestepcheckoutAddress is not defined
Uncaught ReferenceError: OnestepcheckoutShipment is not defined
Uncaught ReferenceError: OnestepcheckoutPayment is not defined
Uncaught ReferenceError: OnestepcheckoutReviewCart is not defined
Uncaught ReferenceError: OnestepcheckoutReviewCoupon is not defined
Uncaught ReferenceError: OnestepcheckoutForm is not defined

**Comment by rafaelstz** [comment]
Você está usando o jQuery do OSC ou do seu tema? Já vi esse erro acontecer da mesma maneira pois o Magento comprime em uma ordem diferente da ordem padrão sem comprimir.

**Comment by rickbenetti** [comment]
jquery meu atualizado, se eu usar do OSC eu quebro o layout todo.

**Comment by rafaelstz** [comment]
Espero que esse link te ajude :+1: 
http://fishpig.co.uk/magento/tutorials/why-you-shouldnt-merge-javascript/

**Comment by rickbenetti** [comment]
Vlw @rafaelstz mas o link não ajuda, na verdade ele empurra o problema com a barriga.
