### ISSUE TITLE
Não completa o endereço e não aparece erro no Console

### ISSUE THREAD

**Issue by diogodaluz** [deivisonarthur/OSC-Magento-Brasil-6-Pro#76]
Fica carregando e não completa os campos de endereço. 
Olhando pelo CONSOLE não aparece erro, vejam se alguém consegue me ajudar:

![erro_cep](https://cloud.githubusercontent.com/assets/11308015/6478953/c24316a2-c21b-11e4-9387-372c861cf265.png)

**Comment by rafaelstz** [comment]
No layout do seu tema vc alterou os atributos dos campos?

**Comment by diogodaluz** [comment]
Estou usando instalação padrão magento 1.9.1 . Nem coloquei tema algum ainda.  Foi o primeiro e único checkout instalado também. alguma ideia?

**Comment by rafaelstz** [comment]
É bem simples o funcionamento do autocompletar, você pode ver como funciona nesse módulo. Há coisas a serem melhoradas nos scripts, mas vai ser bom para te ajudar a entender o funcionamento.
https://github.com/rafaelstz/AutoCompletarEndereco

Você pode colocar um ``console.log `` em cada evento do seu JS para ver aonde ele está parando. :+1:

**Comment by diogodaluz** [comment]
Olha..

Atualizei a versão aqui.. que vi que tinham uns arquivos mais novos... 

E simplesmente sumiu..

Enfim.. obrigado DEUS hahaha

**Comment by rafaelstz** [comment]
:+1:
