### ISSUE TITLE
Problema para autenticar antes de finalizar o pedido

### ISSUE THREAD

**Issue by cesaroito** [deivisonarthur/OSC-Magento-Brasil-6-Pro#81]
Boa noite.

Estou com um problema. Tenho esta loja (www.lacaroty.com.br). Se eu habilito a função Autenticar antes de finalizar o pedido, quando clico no botão finalizar pedido, ele demora 5 minutos para carregar a página. Este problema acontece somente no Mac OS e no IOS. No Windows funciona ok. Se eu desabilito esta função, ele carrega a página onestepcheckout normalmente. Alguém pode me ajudar com isto? Para verificar o problema, peço que façam um teste do Mac por favor.
Obrigado.

**Comment by rafaelstz** [comment]
Tenta refazer o teste em uma janela anônima, testei no mac e foi tudo bem!

**Comment by deivisonarthur** [comment]
Opa Cesar, executa com navegador anonimo, pois aqui foi de boa e rapido.
deve ser cache ai.

http://cloud.inovarti.com.br/image/3H0y0Y2O3h1a

PS Uso mac.

----------

Atenciosamente


*Deivison Arthur L. Serpa*
Founder & CEO Inovarti - Soluções Avançadas em E-commerce


Cel: (21) 99203-8986
Skype: deivisonarthur

sites e blog:

   - br.linkedin.com/pub/deivison-arthur/1b/35/468/
   <http://br.linkedin.com/pub/deivison-arthur/1b/35/468/>
   - https://angel.co/inovarti-advanced-ecommerce-solutions
   - www.deivison.com.br
   - www.inovarti.com.br



"A *Inovarti* <http://www.inovarti.com.br/> é uma empresa que aspira
inovação e para nós o full acompanhamento tecnológico garante a evolução e
crescimento de nossos clientes. Alinhamos nossa exclusiva qualidade
diferenciada com as melhores parceiras tecnológica do mercado."


"É melhor esperar que um programador produtivo torne-se disponível do que
esperar que o primeiro programador disponível torne-se produtivo!"

Em 11 de março de 2015 22:37, cesaroito <notifications@github.com> escreveu:

**Comment by cesaroito** [comment]
Olá Rafael e Deivison,

Eu vi sua imagem, porém eu fiz teste como anônimo e não deu certo. Vou enviar uma tela com o inspect element para vocês verem o que acontece. Vocês irão verificar que leva cerca de 5 minutos para carregar.
![screen shot 2015-03-12 at 6 59 38 am](https://cloud.githubusercontent.com/assets/7848165/6615756/7272e4fc-c885-11e4-8393-461a89f31039.png)
