### ISSUE TITLE
CEP com restrições pela ECT não finaliza pedido.

### ISSUE THREAD

**Issue by GustavoSartori** [deivisonarthur/OSC-Magento-Brasil-6-Pro#86]
Olá. Recebi o contato de uma cliente que não está conseguindo selecionar a forma de entrega. Peguei o CEP dela para testes.
Aqui o erro:
![erro-entrega](https://cloud.githubusercontent.com/assets/8031083/6756827/5584aa24-cf0b-11e4-91ac-f76a40636826.png)

Como podem ver, mesmo o erro sendo em relação ao prazo, e não à impossibilidade de entrega, as opções e valores da entrega não estão sendo exibidas.

Alguém sabe me dizer se isso é bug ou é de propósito?
-- Update
Descobri que pelo backend o problema é o mesmo. Aparece a notificação do prazo, mas não a opção de frete e valor.
![erro-entrega-backend](https://cloud.githubusercontent.com/assets/8031083/6757073/ffeb532c-cf0c-11e4-92a8-3d287007a078.png)

Alguém pode me informar se esse problema ocorre aí também? o CEP é 02356-170

**Comment by rafaelstz** [comment]
Poderia informar o CEP?

**Comment by GustavoSartori** [comment]
Atualizei o post com o CEP ;)

**Comment by rafaelstz** [comment]
Pra mim também está retornando essa mensagem. Na verdade não é um **bug**, e sim uma resposta do WebService dos Correios previamente especificada por eles mesmo.

**Comment by GustavoSartori** [comment]
Eu cheguei à essa conclusão também, mas fiquei intrigado pq não deveria impedir a seleção. Vou procurar algo baseado no módulo dos correios.

**Comment by rafaelstz** [comment]
Esse retorno deve ser novo, nunca ouvi falar disso antes, sendo assim não estava previsto no módulo.

**Comment by GustavoSartori** [comment]
Resolvido o problema @rafaelstz.
Atualizei o módulo dos correios. A versão que tem essa solução é a 1.3.5 e eu tinha 1.3.3.

Fica a dica para quem usa o módulo do Storm! Essa versão (1.3.5) é compatível com área de risco!

**Comment by rafaelstz** [comment]
Vlw :+1:  :smile:
