### ISSUE TITLE
Explicação sobre alguns campos

### ISSUE THREAD

**Issue by kimtiago** [deivisonarthur/OSC-Magento-Brasil-6-Pro#89]
Olá povo,

Sou novato no magento e ainda estou aprendendo, instalei o OSC 6 e estou com dúvidas em 2 campos. Como não encontrei nenhum manual explicativo, vou postar aqui para que me expliquem para que servem:

Mostrar blocos de numeração
Comprar editável no check-out

**Comment by rafaelstz** [comment]
**Mostrar blocos de numeração** Exibe a númeração dos passos 1, 2, 3 e 4
**Comprar editável no check-out** Habilita a possíbilidade do cliente remover ou aumentar a quantidade de produtos em seu carrinho direto do checkout.

**Comment by kimtiago** [comment]
Muito Obrigado!

**Comment by rafaelstz** [comment]
:+1:
