### ISSUE TITLE
Recuperação de senha alerta CPF

### ISSUE THREAD

**Issue by roneclay** [deivisonarthur/OSC-Magento-Brasil-6-Pro#91]
Na troca da versão 4.0 para versão 6 encontramos muitas falhas e uma delas é a recuperação de senha.

Caso o CPF do cliente tenha sido cadastrado via input da versão 4 e TAMBÉM não esteja cadastrado no input TAX/VAT a recuperação de senha não é possível, pois o módulo exige esta informação.

Não seria o caso de, na recuperação de senha, este dado não ser exigido, já que o cliente não conseguirá inserir esta informação, pois esqueceu sua senha?

Todas as nossas lojas estão com esta falha após migrar para versão 6.

Estamos resolvendo isso manualmente inserido o CPF no campo TAX/VAT via admin, mas imagina o transtorno para lojas com mais de 2 mil clientes.

**Comment by isaaclopes** [comment]
ola @roneclay ve se é isso que precisa.
https://github.com/deivisonarthur/OSC-Magento-Brasil-6-Pro/issues/71

**Comment by roneclay** [comment]
@isaaclopes já resolvi criando script para cadastrar o CPF no campo correto.
