### ISSUE TITLE
Problemas ao Logar

### ISSUE THREAD

**Issue by juniordias84** [deivisonarthur/OSC-Magento-Brasil-6-Pro#93]
Galera, blz!

Instalei o módulo na versão 1.8.0.0 e um único probleminha até o momento.

Assim que eu faço o login no checkout, eu me logo, porém a tela permanece como se eu não estivesse logado. Se eu dou um F5 a tela atualiza e muda para como se eu estivesse logado.

Alguém já teve esse mesmo problema ou tem ideia do porque?

Desde já, obrigado!

**Comment by rafaelstz** [comment]
Aparece algum erro no console, pode ser conflito de JS.

**Comment by juniordias84** [comment]
Rafael, blz!

Cara, tratei todos os erros... inclusive do JS.
O console está limpo nesse momento!

**Comment by juniordias84** [comment]
Rafael, blz.
Tem alguma ideia que possa ser além do conflito de JS?

**Comment by rafatriolo** [comment]
Fala galera , boa tarde. 

Primeiramente parabéns pelo módulo , eu utilizo já tem muito tempo. Porém estou com um problema, qdo alguém faz uma compra e se loga no checkout , ele não traz as informações do cliente , mas se eu atualizo a página novamente , fica tudo certo. Já fiz as opções acima e nada resolve. Não tem nenhum conflito de js. Alguem pode me ajudar? abs
