### ISSUE TITLE
Consulta CEP não dá erro mas não retorna nada

### ISSUE THREAD

**Issue by carlosmarchi** [deivisonarthur/OSC-Magento-Brasil-6-Pro#94]
Olá pessoal,

Estou tentando instalar esta versão como um upgrade da 4, está quase tudo funcionando exceto a busca do CEP, que não dá erro mas também não traz os dados, fica em loading eterno. Já tentei ativar/desativar a jQuery do módulo mas não surtiu efeito.

Tentei também instalar em uma instância limpa do Magento 1.9.1 e caí no mesmo problema. Todos os dados da tela são atualizados, mas os campos de endereço não recebem o CEP.

Alguém já encontrou algo parecido ou tem alguma sugestão?

**Comment by rafaelstz** [comment]
O console está dando erro? Verifica se o jQuery está sendo chamado antes dos scripts adicionais, também veja se está funcionando no tema base default do Magento e se os ID´s do campos estão corretos para o JS preencher.

**Comment by carlosmarchi** [comment]
O console não apresenta nenhum erro, o jQuery é do tema e está carregando antes de tudo, já tentei substituir por outras versões e não aconteceu nada também. Com o tema padrão do Magento também acontece a mesma coisa (ícone de load, a página recarrega mas não atualiza os campos). 

Sobre os IDs, parecem certos:
 
<label for="billing:street1" class="required"><em>*</em>Endereço</label>
<input type="text" title="Endereço" name="billing[street][]" id="billing:street1" class="input-text  required-entry" value="" autocomplete="off">

E depois 2, 3 e 4 respectivamente.

Sim, OSC baixado aqui do Git ontem. Já tentei subir os arquivos de novo também mas sem resultados.

**Comment by rafaelstz** [comment]
Tem ambiente de teste?

**Comment by carlosmarchi** [comment]
http://ec2-54-94-233-80.sa-east-1.compute.amazonaws.com/onestepcheckout/index/

Esta é uma instalação nova, só tem o OSC e o Tema instalados. Desativando o tema o problema permanece, tanto com o base quanto no rwd.

**Comment by rafaelstz** [comment]
Está dando certo agora, no começo dos meus testes não estava. O retorno da API estava dando certo também.

**Comment by carlosmarchi** [comment]
O problema era externo então, naquela URL que faz a busca?

**Comment by rafaelstz** [comment]
Desde que comecei testar estava obtendo o retorno correto, por isso não acredito que ela seja o problema.
Conforme fui testando funcionou.

**Comment by carlosmarchi** [comment]
Bizarro ... e no ambiente de produção funcionou também, sem mexer em nada. 

Obrigado!

**Comment by deniscsz** [comment]
Se não me engano semana passada a página dos Correios que o módulo puxa as
informações estava com problemas. Quando normalizou nos Correios, voltou a
funcionar.

**Comment by Chicodarave** [comment]
Prezados, estou com uma instalação limpa do Magento 1.9.2.2 em localhost.
Está no root, instalei SOMENTE o OSC 6 e a tradução do MarioSam.
O tema é o padrão do Magento (RWD).
Não fiz nenhuma modificação.
A validação de CPF e e-mail passou sem nenhuma alteração, porém tá dando problema no CEP e o botão "Finalizar Pedido" não funciona.
O que faço?
Obrigado.

Edit: Apagando app\design\frontend\rwd\default\template\onestepcheckout\onestep.phtml fez o botão "Finalizar Pedido" funcionar, mas não sei se isso é um procedimento correto.
Porém isso não resolveu o problema do CEP.
Ao realizar o procedimento do CEP com o console aberto o erro que recebo é:
http://127.0.0.1/customer/address/editajax/busca_cep?cep=88103970&_=1456471482595 404 (Not Found)
