### ISSUE TITLE
Método para pegar o CPF

### ISSUE THREAD

**Issue by kimtiago** [deivisonarthur/OSC-Magento-Brasil-6-Pro#97]
Isso não é um problema do módulo, é uma dúvida que eu e mais algumas pessoas estão tendo.

Uso o modulo de boleto bancário do Eric e preciso colocar o CPF no boleto. Coisa que o modulo não faz usando em conjunto com o OSC. Logo estou tendo que editar o código para conseguir fazer isso. Porém não consegui descobrir um metodo para PEGAR O TAX/VAT que é o valor do CPF.

Testei
$billing  = $this->getOrder()->getBillingAddress();
$billing->getVatId();

Porém não funciona. Alguem por favor me diz qual metódo pega o TAX/VAT (CPF)?

**Comment by rafaelstz** [comment]
No começo checa se o cliente está logado ou não, então em seguida instância o objeto.

```php
if (Mage::getSingleton('customer/session')->isLoggedIn()) {
    $customer = Mage::getSingleton('customer/session')->getCustomer();
    $customerData = Mage::getModel('customer/customer')->load($customer->getId())->getData();
    Mage::log($customerData);
}
```

Atráves disso ele retorna:

```php
Array
(
    [entity_id] => 1
    [entity_type_id] => 1
    [attribute_set_id] => 0
    [website_id] => 1
    [email] => john.doe@example.com
    [group_id] => 1
    [increment_id] => 000000001
    [store_id] => 1
    [created_at] => 2007-08-30 23:23:13
    [updated_at] => 2008-08-08 12:28:24
    [is_active] => 1
    [firstname] => John
    [lastname] => Doe
    [password_hash] => 204948a4020ed1d0e4238db2277d5:eg
    [prefix] => 
    [middlename] => 
    [suffix] => 
    [taxvat] => 
    [default_billing] => 274
    [default_shipping] => 274
)

```

E você poderá usar assim:

```php
$customerID = $customerData->getId(); //entity_id can be used as id
$name = $customerData->getFirstname() . ' ' . $customerData->getLastname();
$isActive = $customerData->getIsActive();
$email = $customerData->getEmail();
$incrId = $customerData->getIncrementId();
```

Boa sorte :smile: :+1:

**Comment by kimtiago** [comment]
Obrigado pela ajuda Rafael, consegui resolver de uma forma que não precisasse mexer muito no código. Fiz assim:

_______________________________________________________________________________
No arquivo "/app/code/community/MageBR/BoletoBancario/Model/Standard.php" alterei

```
// PEGA O CPF DO CLIENTE PARA IMPRIMIR NO BOLETO (OSC6)
$taxvat = $order->getData('customer_taxvat');

// ISSO AQUI JÁ ESTÁ NO CÓDIGO, NÃO ALTERAR
$a = $order->getBillingAddress();

...
...

// COLOCA O CPF DO CLIENTE E JOGA NA VARIÁVEL CORRESPONDENTE
'cliente_cpf' => $taxvat,
```

**Comment by sergionauffal** [comment]
kimtiago commented on 21 Apr 2015
Parabéns pelo seu código kimtiago, utilizando em 2017, que é obrigatório o boleto ser Com Registro e mostrar o CPF/CNPJ e funcionando perfeitamente.
OBS. Lembrando que o código deve ser usado, também, no Emissor de 2a via do Módulo Boleto com 2a via para o Magento Community!
